services:
  reverse-proxy:
    image: traefik:v2.11.2
    restart: always
    command: --api.insecure=true --providers.docker
    # command: --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy-net
  # redirect:
  #   image: morbz/docker-web-redirect
  #   restart: always
  #   expose:
  #     - 80
  #   labels:
  #     - traefik.http.routers.main-redirect.rule=Host(`10.10.10.1`)
  #     - traefik.http.services.main-redirect-service.loadbalancer.server.port=80
  #     - traefik.docker.network=local-reverse-proxy-net
  #   environment:
  #     - REDIRECT_TARGET=mydomain.net
  #   networks:
  #     - reverse-proxy-net
networks:
  reverse-proxy-net:
    name: "local-reverse-proxy-net"
    external: true