services:
  reverse-proxy:
    image: traefik:v3.0.0
    restart: always
    environment:
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_PROVIDERS_DOCKER_EXPOSEDBYDEFAULT=false
      # - TRAEFIK_API_INSECURE=true
      # - TRAEFIK_EXPERIMENTAL_PLUGINS_cloudflarewarp_MODULENAME=github.com/BetterCorp/cloudflarewarp
      # - TRAEFIK_EXPERIMENTAL_PLUGINS_cloudflarewarp_VERSION=v1.3.3
    ports:
      - "80:80"
      # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy-net
  # redirect:
  #   image: morbz/docker-web-redirect
  #   restart: always
  #   expose:
  #     - 80
  #   labels:
  #     - traefik.http.routers.main-redirect.rule=Host(`10.10.10.1`)
  #     - traefik.http.services.main-redirect-service.loadbalancer.server.port=80
  #     - traefik.docker.network=local-reverse-proxy-net
  #   environment:
  #     - REDIRECT_TARGET=mydomain.net
  #   networks:
  #     - reverse-proxy-net
networks:
  reverse-proxy-net:
    name: "local-reverse-proxy-net"
    external: true