services:
  reverse-proxy:
    image: traefik:v2.11.2
    restart: always
    command: --api.insecure=true --providers.docker
    # command: --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy-net
networks:
  reverse-proxy-net:
    name: "local-reverse-proxy-net"
    external: true