#!/bin/bash

set -e

pushd ${0%/*}

COMMAND=$1
if [ $# -gt 0 ]; then
    shift
fi

DOCKER_COMPOSE_CMD="sudo docker compose"

BASH_CMD="sh ./live-proxy"

if [ "$COMMAND" = "up" ]; then
    $DOCKER_COMPOSE_CMD up -d
elif [ "$COMMAND" = "down" ]; then
    $DOCKER_COMPOSE_CMD down
elif [ "$COMMAND" = "restart" ]; then
    set +e
    $BASH_CMD down
    set -e
    $BASH_CMD up
else
    if [ -n "$COMMAND" ]; then
        echo "ERROR: \`$COMMAND\` is invalid option."
        echo
    fi
    echo "┌─────────────────────────────────────┐"
    echo "│ Available options:                  │"
    echo "│ - up                                │"
    echo "│ - down                              │"
    echo "│ - restart                           │"
    echo "└─────────────────────────────────────┘"
fi